### ISSUE TITLE
Remove selected game

### ISSUE THREAD

**Issue by NecroGankedd** [Bob123a1/CDNSP-GUI#15] opened 2018-08-17 22:22 UTC
**Describe the bug**
Selecting the option "Remove Selected Game" removes the title from the Queue Menu however it does not prevent the title from being downloaded in the order it was in originally. 

**To Reproduce**
1. Add some titles to the queue.
2. Begin downloading titles.
3. Remove one or more titles from the queue
4. Add a new title to the queue.
5. Before the new title starts downloading the previously deleted title will begin first.

**Expected behavior**
When a title is removed from the Queue Menu it should not begin a download of that title. 

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 17134.191
 - Version CDNSP GUI - Bobv4.1.1

**Comment by griest024** [comment] 2018-08-18 04:44
When "download all" is pressed, the data structure containing the list of titles is copied and sent to the download function. It *must* be copied, because you can't (or shouldn't) change a list while iterating through it.

This is probably going to be a wontfix because of how annoying it would be to implement. It would probably introduce a lot of regressions.

You can easily work around this by restarting the program, removing or adding games, and then starting the download again. CDNSP can resume downloads so you won't lose any download progress.

**Comment by NecroGankedd** [comment] 2018-08-18 04:56
Ah, well that does make sense then. I was a little wary to post this as an issue. 

For the time being I will refrain from iterating upon my lists as they're in progress.

**Comment by griest024** [comment] 2018-08-18 16:43
No you misunderstand. Iterating is what the download function does to the list. What you need to do is not *change* the list while it's being iterated.

But it doesn't matter because like I said, the list is copied before it is sent to the download function. So you no longer have any way to change the list. The list that backs the queue and the list that the download function has are separate and distinct

**Closed** 2018-10-09 10:29 UTC
